# Generated by Django 4.1.7 on 2023-04-20 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone1', models.CharField(max_length=12, null=True)),
                ('phone2', models.CharField(max_length=12, null=True, unique=True)),
                ('phone3', models.CharField(max_length=12, null=True, unique=True)),
                ('cell1', models.CharField(max_length=12, null=True, unique=True)),
                ('cell2', models.CharField(max_length=12, null=True, unique=True)),
                ('kanjiname', models.CharField(default=None, max_length=50, null=True)),
                ('kanjilastname', models.CharField(default=None, max_length=50, null=True)),
                ('kananame', models.CharField(default=None, max_length=50, null=True)),
                ('kanalastname', models.CharField(default=None, max_length=50)),
                ('dob', models.DateField(default=None, null=True)),
                ('gender', models.CharField(default=None, max_length=50, null=True)),
                ('add1', models.CharField(max_length=50, null=True)),
                ('add2', models.CharField(max_length=50, null=True)),
                ('add3', models.CharField(default=None, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
            ],
        ),
    ]
