# Generated by Django 4.1.7 on 2023-04-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_api', '0002_alter_customer_phone2'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cell3',
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
    ]
