# Generated by Django 4.1.7 on 2023-05-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_api', '0003_customer_cell3'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonCustInfo',
            fields=[
                ('customer_no', models.TextField(primary_key=True, serialize=False)),
                ('first_name_kanji', models.TextField(blank=True, null=True)),
                ('last_name_kanji', models.TextField(blank=True, null=True)),
                ('first_name_kana', models.TextField(blank=True, null=True)),
                ('last_name_kana', models.TextField(blank=True, null=True)),
                ('gender', models.TextField(blank=True, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('phone_area_code', models.TextField(blank=True, null=True)),
                ('phone_local_area_code', models.TextField(blank=True, null=True)),
                ('phone_no', models.TextField(blank=True, null=True)),
                ('cellphone_no1', models.TextField(blank=True, null=True)),
                ('cellphone_no2', models.TextField(blank=True, null=True)),
                ('cellphone_no3', models.TextField(blank=True, null=True)),
                ('email_pc', models.TextField(blank=True, null=True)),
                ('email_opt_flag', models.TextField(blank=True, null=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.TextField(blank=True, null=True)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
                ('del_flg', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
